import { Exercise } from "@/lib/types/training"

// Datos de ejercicios con URLs de GIFs para demostración
export const exerciseData: Exercise[] = [
  {
    id: "bench-press",
    name: "Press de banca",
    description: "Ejercicio compuesto para el desarrollo del pecho, hombros y tríceps.",
    category: "chest",
    equipment: ["barbell"],
    muscleGroup: ["chest", "shoulders", "triceps"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-bench-press-benefits.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-bench-press-benefits.gif",
    alternatives: ["dumbbell-press", "push-up", "incline-bench-press"]
  },
  {
    id: "squat",
    name: "Sentadilla",
    description: "Ejercicio compuesto para el desarrollo de piernas y glúteos.",
    category: "legs",
    equipment: ["barbell"],
    muscleGroup: ["quads", "hamstrings", "glutes"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/barbell-full-squat.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/03/barbell-full-squat.gif",
    alternatives: ["leg-press", "goblet-squat", "hack-squat"]
  },
  {
    id: "deadlift",
    name: "Peso muerto",
    description: "Ejercicio compuesto para el desarrollo de espalda, piernas y core.",
    category: "back",
    equipment: ["barbell"],
    muscleGroup: ["back", "hamstrings", "glutes", "core"],
    difficulty: "advanced",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-deadlift.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-deadlift.gif",
    alternatives: ["romanian-deadlift", "sumo-deadlift", "rack-pull"]
  },
  {
    id: "pull-up",
    name: "Dominadas",
    description: "Ejercicio compuesto para el desarrollo de espalda y bíceps.",
    category: "back",
    equipment: ["bodyweight"],
    muscleGroup: ["back", "biceps", "forearms"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/pull-up.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/pull-up.gif",
    alternatives: ["lat-pulldown", "chin-up", "assisted-pull-up"]
  },
  {
    id: "overhead-press",
    name: "Press militar",
    description: "Ejercicio compuesto para el desarrollo de hombros y tríceps.",
    category: "shoulders",
    equipment: ["barbell"],
    muscleGroup: ["shoulders", "triceps"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-overhead-press.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-overhead-press.gif",
    alternatives: ["dumbbell-shoulder-press", "arnold-press", "push-press"]
  },
  {
    id: "barbell-row",
    name: "Remo con barra",
    description: "Ejercicio compuesto para el desarrollo de espalda y bíceps.",
    category: "back",
    equipment: ["barbell"],
    muscleGroup: ["back", "biceps", "forearms"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-bent-over-row.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/barbell-bent-over-row.gif",
    alternatives: ["dumbbell-row", "cable-row", "t-bar-row"]
  },
  {
    id: "dumbbell-press",
    name: "Press con mancuernas",
    description: "Variante del press de banca con mancuernas para mayor rango de movimiento.",
    category: "chest",
    equipment: ["dumbbell"],
    muscleGroup: ["chest", "shoulders", "triceps"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-bench-press.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-bench-press.gif",
    alternatives: ["bench-press", "push-up", "incline-dumbbell-press"]
  },
  {
    id: "leg-press",
    name: "Prensa de piernas",
    description: "Ejercicio para el desarrollo de piernas con menor estrés en la espalda.",
    category: "legs",
    equipment: ["machine"],
    muscleGroup: ["quads", "hamstrings", "glutes"],
    difficulty: "beginner",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/leg-press.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/leg-press.gif",
    alternatives: ["squat", "hack-squat", "goblet-squat"]
  },
  {
    id: "lat-pulldown",
    name: "Jalón al pecho",
    description: "Ejercicio para el desarrollo de la espalda, alternativa a las dominadas.",
    category: "back",
    equipment: ["cable"],
    muscleGroup: ["back", "biceps"],
    difficulty: "beginner",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/lat-pulldown.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/lat-pulldown.gif",
    alternatives: ["pull-up", "straight-arm-pulldown", "machine-pulldown"]
  },
  {
    id: "dumbbell-curl",
    name: "Curl de bíceps con mancuernas",
    description: "Ejercicio de aislamiento para el desarrollo de bíceps.",
    category: "arms",
    equipment: ["dumbbell"],
    muscleGroup: ["biceps", "forearms"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-bicep-curl.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-bicep-curl.gif",
    alternatives: ["barbell-curl", "hammer-curl", "preacher-curl"]
  },
  {
    id: "triceps-pushdown",
    name: "Extensiones de tríceps en polea",
    description: "Ejercicio de aislamiento para el desarrollo de tríceps.",
    category: "arms",
    equipment: ["cable"],
    muscleGroup: ["triceps"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/triceps-pushdown.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/triceps-pushdown.gif",
    alternatives: ["skull-crusher", "dips", "overhead-triceps-extension"]
  },
  {
    id: "lateral-raise",
    name: "Elevaciones laterales",
    description: "Ejercicio de aislamiento para el desarrollo de los deltoides laterales.",
    category: "shoulders",
    equipment: ["dumbbell"],
    muscleGroup: ["shoulders"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-lateral-raise.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/dumbbell-lateral-raise.gif",
    alternatives: ["cable-lateral-raise", "machine-lateral-raise", "upright-row"]
  },
  {
    id: "leg-extension",
    name: "Extensiones de piernas",
    description: "Ejercicio de aislamiento para el desarrollo del cuádriceps.",
    category: "legs",
    equipment: ["machine"],
    muscleGroup: ["quads"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/leg-extension.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/leg-extension.gif",
    alternatives: ["sissy-squat", "front-squat", "bulgarian-split-squat"]
  },
  {
    id: "leg-curl",
    name: "Curl de piernas",
    description: "Ejercicio de aislamiento para el desarrollo de isquiotibiales.",
    category: "legs",
    equipment: ["machine"],
    muscleGroup: ["hamstrings"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/lying-leg-curl.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/lying-leg-curl.gif",
    alternatives: ["romanian-deadlift", "good-morning", "nordic-curl"]
  },
  {
    id: "calf-raise",
    name: "Elevaciones de gemelos",
    description: "Ejercicio de aislamiento para el desarrollo de pantorrillas.",
    category: "legs",
    equipment: ["machine", "bodyweight"],
    muscleGroup: ["calves"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/standing-calf-raise.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/standing-calf-raise.gif",
    alternatives: ["seated-calf-raise", "donkey-calf-raise", "leg-press-calf-raise"]
  },
  {
    id: "crunch",
    name: "Abdominales",
    description: "Ejercicio básico para el desarrollo de los abdominales.",
    category: "abs",
    equipment: ["bodyweight"],
    muscleGroup: ["abs"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/crunch.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/crunch.gif",
    alternatives: ["sit-up", "leg-raise", "plank"]
  },
  {
    id: "push-up",
    name: "Flexiones",
    description: "Ejercicio básico con peso corporal para pecho, hombros y tríceps.",
    category: "chest",
    equipment: ["bodyweight"],
    muscleGroup: ["chest", "shoulders", "triceps"],
    difficulty: "beginner",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/push-up.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/push-up.gif",
    alternatives: ["bench-press", "dumbbell-press", "incline-push-up"]
  },
  {
    id: "dips",
    name: "Fondos",
    description: "Ejercicio compuesto para tríceps y pecho inferior.",
    category: "chest",
    equipment: ["bodyweight"],
    muscleGroup: ["chest", "triceps", "shoulders"],
    difficulty: "intermediate",
    isCompound: true,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/triceps-dips.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/triceps-dips.gif",
    alternatives: ["close-grip-bench-press", "diamond-push-up", "triceps-pushdown"]
  },
  {
    id: "face-pull",
    name: "Face pull",
    description: "Ejercicio para el desarrollo de la parte posterior de los hombros y trapecio.",
    category: "shoulders",
    equipment: ["cable"],
    muscleGroup: ["shoulders", "traps", "upper-back"],
    difficulty: "intermediate",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/face-pull.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/face-pull.gif",
    alternatives: ["reverse-fly", "band-pull-apart", "rear-delt-row"]
  },
  {
    id: "plank",
    name: "Plancha",
    description: "Ejercicio isométrico para el desarrollo del core.",
    category: "abs",
    equipment: ["bodyweight"],
    muscleGroup: ["abs", "core"],
    difficulty: "beginner",
    isCompound: false,
    imageUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/plank.gif",
    videoUrl: "https://www.inspireusafoundation.org/wp-content/uploads/2022/01/plank.gif",
    alternatives: ["side-plank", "ab-wheel-rollout", "hollow-hold"]
  }
]
